{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pv-portal.fullname" . }}-secret
  labels:
    {{- include "pv-portal.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.url }}
  DATABASE_URL: {{ .Values.database.url | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.jwtSecret }}
  JWT_SECRET: {{ .Values.auth.jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if and .Values.redis.enabled .Values.redis.url }}
  REDIS_URL: {{ .Values.redis.url | b64enc | quote }}
  {{- end }}
  {{- if and (eq .Values.artifactStore.backend "s3") .Values.artifactStore.s3.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.artifactStore.s3.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.artifactStore.s3.secretAccessKey | b64enc | quote }}
  {{- end }}
{{- end }}
