apiVersion: v1
kind: Service
metadata:
  name: {{ include "pv-portal.fullname" . }}-api
  labels:
    {{- include "pv-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "pv-portal.api.selectorLabels" . | nindent 4 }}
